export const SAVE_INSTAGRAM_TOKEN = 'SAVE_INSTAGRAM_TOKEN';

export const LOGIN = 'LOGIN';

export const ADD_HASHTAG = 'ADD_HASHTAG';

export const ADD_PEOPLE = 'ADD_PEOPLE';

export const ADD_USER = 'ADD_USER';

export const FETCH_USER_DATA = 'FETCH_USER_DATA';

export const SET_INFLUENCE_DATA = 'SET_INFLUENCE_DATA';

export const SET_PERFORMANCE_DATA = 'SET_PERFORMANCE_DATA';
